#!/bin/bash

#This file is expected to live in <root-folder>/scripts, so
source "$(dirname $0)/common"

cd $ROOT_PATH

# Delete the folder used hosting livereload server
rm -rf public

# Delete all the files used for distribution
find . -maxdepth 1 -name "*zip" -delete

