#!/bin/bash
source "$(dirname $0)/common"

# check that we are in a virtual environment
python  $(dirname $0)/check_venv.py

if ! [ $? -eq 0 ]
then
  echo "someh"
  echo "Not running inside virtualenv, create virtualenv first before running setup command. See README.md for more details"
fi

echo "Running inside virtualenv"
pip -V

echo "Installing pip requirements"
# First, make sure requirements are installed
pip install -r requirements.txt

echo "Download nltk corpora"
# Then make sure that NLTK Data is present
python -m textblob.download_corpora
